type User {
    id: ID!
    firstName: String!
    lastName: String!
    fullName: String!
    email: String!
    active: Boolean
    createdAt: String
}

input UserInput {
    firstName: String!
    lastName: String!
    email: String!
    active: Boolean!
}

type Query {
    users: [User!]!
    user(id: ID!): User!
}

type Mutation {
    createUser(data: UserInput): User!
    updateUser(id: ID!, data: UserInput): User!
    deleteUser(id: ID!): Boolean
}